import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { chmod, mkdir, mkdtemp, realpath, rm, symlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { test } from 'node:test';

import { captureInputs, compareInputs } from '../scripts/verification/inputs.mjs';

function git(cwd: string, args: string[], input?: string) {
  return execFileSync('git', args, { cwd, input, encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'] }).trim();
}

async function fixture(t: { after: (fn: () => Promise<void>) => void }) {
  const root = await realpath(await mkdtemp(join(tmpdir(), 'repro-dev-inputs-')));
  t.after(() => rm(root, { recursive: true, force: true }));
  for (const dir of ['src', 'docs', 'fixtures', 'examples/output']) await mkdir(join(root, dir), { recursive: true });
  for (const [path, text] of Object.entries({
    'src/index.ts': 'export const value = 1;\n',
    'docs/guide.md': '# Guide\n',
    'docs/example.TXT': 'a text fixture\n',
    'fixtures/ignored.txt': 'an ignored input\n',
    'examples/output/expected.txt': 'expected fixture output\n',
    'LICENSE': 'license text\n',
    '.gitignore': 'fixtures/ignored.txt\n.local/\nnode_modules/\n',
  })) await writeFile(join(root, path), text);
  git(root, ['init', '-q']);
  git(root, ['config', 'user.name', 'Input Tests']);
  git(root, ['config', 'user.email', 'inputs@example.test']);
  git(root, ['add', '.']);
  git(root, ['commit', '-qm', 'fixture']);
  return root;
}

test('captures real input bytes and full Git identity while stage and commit preserve freshness', async (t) => {
  const root = await fixture(t);
  const before = await captureInputs(root);
  assert.equal(before.available, true, before.reason);
  assert.equal(before.root, root);
  assert.equal(before.head, git(root, ['rev-parse', 'HEAD']));
  assert.match(before.tree, /^[a-f0-9]{64}$/);
  assert.equal(before.stalegreen.available, true);
  assert.equal(compareInputs(before, await captureInputs(root)), 'same');
  await writeFile(join(root, 'src/index.ts'), 'export const value = 2;\n');
  const edited = await captureInputs(root);
  assert.equal(compareInputs(before, edited), 'different');
  git(root, ['add', '.']);
  assert.equal(compareInputs(edited, await captureInputs(root)), 'same');
  git(root, ['commit', '-qm', 'edit']);
  const committed = await captureInputs(root);
  assert.notEqual(edited.head, committed.head);
  assert.equal(compareInputs(edited, committed), 'same');
});

test('documentation, text, license, ignored fixtures and nested output are all relevant inputs', async (t) => {
  const root = await fixture(t);
  for (const path of ['docs/guide.md', 'docs/example.TXT', 'LICENSE', 'fixtures/ignored.txt', 'examples/output/expected.txt']) {
    const before = await captureInputs(root);
    await writeFile(join(root, path), `changed ${path}\n`);
    const after = await captureInputs(root);
    assert.equal(after.available, true, after.reason);
    assert.equal(compareInputs(before, after), 'different', path);
  }
});

test('assume-unchanged file edits cannot hide behind the Git index', async (t) => {
  const root = await fixture(t);
  git(root, ['update-index', '--assume-unchanged', 'src/index.ts']);
  const before = await captureInputs(root);
  await writeFile(join(root, 'src/index.ts'), 'export const value = 3;\n');
  const after = await captureInputs(root);
  assert.equal(compareInputs(before, after), 'different');
});

test('executable permission changes invalidate evidence', { skip: process.platform === 'win32' }, async (t) => {
  const root = await fixture(t);
  const before = await captureInputs(root);
  await chmod(join(root, 'src/index.ts'), 0o755);
  assert.equal(compareInputs(before, await captureInputs(root)), 'different');
});

test('generated and private output never invalidates its own evidence', async (t) => {
  const root = await fixture(t);
  const before = await captureInputs(root);
  for (const dir of ['.local', 'dist', 'coverage', 'output', '.repro-surgeon', '.superpowers', '.impeccable', 'node_modules', 'examples/node_modules']) {
    await mkdir(join(root, dir), { recursive: true });
    await writeFile(join(root, dir, 'generated.txt'), 'new evidence\n');
  }
  for (const path of ['AGENTS.md', 'archive.tgz', '.DS_Store', 'docs/.DS_Store']) await writeFile(join(root, path), 'private generated bytes');
  const after = await captureInputs(root);
  assert.equal(after.available, true, after.reason);
  assert.equal(compareInputs(before, after), 'same');
});

test('nested AGENTS, archive files and directories named like generated root output remain inputs', async (t) => {
  const root = await fixture(t);
  for (const path of ['docs/AGENTS.md', 'docs/archive.tgz', 'docs/output.txt']) {
    const before = await captureInputs(root);
    await writeFile(join(root, path), 'included\n');
    assert.equal(compareInputs(before, await captureInputs(root)), 'different', path);
  }
});

test('missing roots, non-repositories and repository subdirectories are unavailable', async (t) => {
  const root = await fixture(t);
  for (const path of [join(root, 'missing'), join(root, 'src'), tmpdir()]) {
    const result = await captureInputs(path);
    assert.equal(result.available, false, path);
    assert.equal(result.tree, null);
    assert.ok(result.reason);
  }
});

test('unborn HEAD, exhausted budgets and file or byte limits cannot produce a fresh fingerprint', async (t) => {
  const root = await fixture(t);
  const before = await captureInputs(root);
  for (const options of [{ budgetMs: 0 }, { budgetMs: 1 }, { maxFiles: 1 }, { maxBytes: 1 }, { budgetMs: NaN }, { maxFiles: -1 }]) {
    const result = await captureInputs(root, options);
    assert.equal(result.available, false, JSON.stringify(options));
    assert.equal(result.tree, null);
    assert.equal(compareInputs(before, result), 'unknown');
  }
  const empty = await mkdtemp(join(tmpdir(), 'repro-unborn-'));
  t.after(() => rm(empty, { recursive: true, force: true }));
  git(empty, ['init', '-q']);
  assert.equal((await captureInputs(empty)).available, false);
});

test('symlinked inputs are unavailable rather than followed or silently omitted', async (t) => {
  const root = await fixture(t);
  await symlink('../src/index.ts', join(root, 'docs/link.ts'));
  const result = await captureInputs(root);
  assert.equal(result.available, false);
  assert.match(result.reason, /symlink/i);
});

test('submodules are unavailable even without a populated working directory', async (t) => {
  const root = await fixture(t);
  git(root, ['update-index', '--add', '--cacheinfo', `160000,${git(root, ['rev-parse', 'HEAD'])},submodule`]);
  const result = await captureInputs(root);
  assert.equal(result.available, false);
  assert.match(result.reason, /submodule/i);
});

test('unresolved Git index stages are unavailable', async (t) => {
  const root = await fixture(t);
  const blob = git(root, ['rev-parse', 'HEAD:src/index.ts']);
  git(root, ['update-index', '--index-info'], `0 ${'0'.repeat(40)}\tsrc/index.ts\n100644 ${blob} 1\tsrc/index.ts\n100644 ${blob} 2\tsrc/index.ts\n`);
  const result = await captureInputs(root);
  assert.equal(result.available, false);
  assert.match(result.reason, /unresolved/i);
});

test('special files cannot turn into a passing incomplete snapshot', { skip: process.platform === 'win32' }, async (t) => {
  const root = await fixture(t);
  execFileSync('mkfifo', [join(root, 'fixture-pipe')]);
  const result = await captureInputs(root);
  assert.equal(result.available, false);
  assert.match(result.reason, /special/i);
});

test('unavailable or malformed saved fingerprints never compare as fresh', async (t) => {
  const root = await fixture(t);
  const before = await captureInputs(root);
  for (const invalid of [undefined, {}, { ...before, tree: null }, { ...before, policy: 'other' }, { ...before, root: root + '/other' }, { ...before, stalegreen: { available: true, tree: null } }, { ...before, head: null }, { ...before, tree: [before.tree] }, { ...before, head: [before.head] }, { ...before, stalegreen: { ...before.stalegreen, tree: [before.stalegreen.tree] } }]) {
    assert.equal(compareInputs(before, invalid), 'unknown');
  }
});


test('linked worktrees retain their own root and full HEAD', async (t) => {
  const root = await fixture(t);
  const parent = await mkdtemp(join(tmpdir(), 'repro-linked-inputs-'));
  t.after(() => rm(parent, { recursive: true, force: true }));
  const linked = join(parent, 'checkout');
  git(root, ['worktree', 'add', '--detach', linked, 'HEAD']);
  const result = await captureInputs(linked);
  assert.equal(result.available, true, result.reason);
  assert.equal(result.root, await realpath(linked));
  assert.equal(result.head, git(root, ['rev-parse', 'HEAD']));
});

test('missing Git cannot silently degrade to a fresh filesystem hash', async (t) => {
  const root = await fixture(t);
  const module = new URL('../scripts/verification/inputs.mjs', import.meta.url).href;
  const output = execFileSync(process.execPath, ['--input-type=module', '-e',
    `import { captureInputs } from ${JSON.stringify(module)}; console.log(JSON.stringify(await captureInputs(${JSON.stringify(root)})));`,
  ], { encoding: 'utf8', env: { ...process.env, PATH: '' } });
  const result = JSON.parse(output);
  assert.equal(result.available, false);
  assert.equal(result.tree, null);
  assert.match(result.reason, /git.*unavailable/i);
});

test('unreadable included files are unavailable rather than dropped', { skip: process.platform === 'win32' || process.getuid?.() === 0 }, async (t) => {
  const root = await fixture(t);
  await chmod(join(root, 'fixtures/ignored.txt'), 0);
  const result = await captureInputs(root);
  assert.equal(result.available, false);
  assert.equal(result.tree, null);
  assert.match(result.reason, /EACCES|permission/i);
});

test('an included input changing during a capture is unavailable', async (t) => {
  const root = await fixture(t);
  await writeFile(join(root, 'src/changing.bin'), Buffer.alloc(8 * 1024 * 1024));
  let running = true;
  const writer = (async () => {
    let value = 0;
    while (running) {
      await writeFile(join(root, 'src/changing.bin'), Buffer.alloc(8 * 1024 * 1024, value++ % 255));
    }
  })();
  try {
    const result = await captureInputs(root);
    assert.equal(result.available, false);
    assert.equal(result.tree, null);
    assert.match(result.reason, /changed|budget/i);
  } finally {
    running = false;
    await writer;
  }
});
